<script setup>
import { computed, onMounted, ref } from 'vue'; import api from '../api'
const products=ref([]), cart=ref([]), error=ref(''), success=ref(''), loading=ref(false)
const total=computed(()=>cart.value.reduce((sum,l)=>sum+Number(l.product.sale_price)*l.quantity*(1+Number(l.product.tax_rate)/100),0))
async function load(){try{products.value=(await api.get('/products')).data}catch(e){error.value=e.response?.data?.detail}}
function add(product){let line=cart.value.find(l=>l.product.id===product.id);if(line){if(line.quantity<Number(product.stock))line.quantity++}else if(Number(product.stock)>0)cart.value.push({product,quantity:1})}
async function checkout(){loading.value=true;error.value='';try{let {data}=await api.post('/sales',{lines:cart.value.map(l=>({product_id:l.product.id,quantity:l.quantity}))});success.value=`Venta ${data.number} registrada por $${data.total}`;cart.value=[];await load()}catch(e){error.value=e.response?.data?.detail}finally{loading.value=false}}
onMounted(load)
</script>
<template><h1 class="mb-5">Punto de venta</h1><v-alert v-if="error" type="error" closable class="mb-4">{{error}}</v-alert><v-alert v-if="success" type="success" closable class="mb-4">{{success}}</v-alert><v-row><v-col cols="12" md="7"><v-row><v-col v-for="p in products" :key="p.id" cols="12" sm="6" lg="4"><v-card height="150" class="pa-2" @click="add(p)" :disabled="Number(p.stock)<=0"><v-card-title>{{p.name}}</v-card-title><v-card-subtitle>{{p.sku}} · Stock {{p.stock}}</v-card-subtitle><v-card-text class="text-h5 text-primary">${{p.sale_price}}</v-card-text></v-card></v-col></v-row></v-col><v-col cols="12" md="5"><v-card class="pa-4" position="sticky" style="top:80px"><v-card-title>Venta actual</v-card-title><v-list><v-list-item v-for="line in cart" :key="line.product.id" :title="line.product.name" :subtitle="`$${line.product.sale_price}`"><template #append><v-number-input v-model="line.quantity" :min="1" :max="Number(line.product.stock)" width="120" control-variant="split"/><v-btn icon="mdi-delete" variant="text" color="error" @click="cart=cart.filter(l=>l!==line)"/></template></v-list-item></v-list><v-divider/><div class="text-h4 text-right my-5">Total ${{total.toFixed(2)}}</div><v-btn block size="large" color="primary" :disabled="!cart.length" :loading="loading" @click="checkout">Cobrar venta</v-btn></v-card></v-col></v-row></template>

